services:
  postgres:
    image: 'postgres:15.6-alpine3.19'
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: 'fastify-mikro/be'
    deploy:
      resources:
        limits:
          memory: 150M
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres_password
volumes:
  pg_data:
    driver: local
