services:
  backend:
    image: 'fastify-mikro/be'
    deploy:
      resources:
        limits:
          memory: 150M
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
