services:
  postgres:
    image: 'postgres:15.6-alpine3.19'
    deploy:
      resources:
        limits:
          memory: 100M
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: 'fastify-mikro/fe'
    deploy:
      resources:
        limits:
          memory: 150M
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
volumes:
  pg_data:
    driver: local
